### PR TITLE
Use Node 20

### PR DESCRIPTION
**Pull request by AegirLeet**
---
name: ⚙ Improvement
about: Use Node 20
labels: enhancement

---

### Description

Node 16 is EOL - use Node 20 instead.
Also adds a missing step to the contributing guidelines.

### CODE REVIEW

**Comment by shivammathur** [comment]
@AegirLeet Please update the node version in the workflow as well.
https://github.com/shivammathur/cache-extensions/blob/master/.github/workflows/node-test.yml#L20

**Comment by AegirLeet** [comment]
@shivammathur Will do. https://github.com/shivammathur/cache-extensions/blob/master/.github/workflows/node-release.yml#L33 as well?

**Comment by AegirLeet** [comment]
I've updated the test workflow, release workflow and setup-node action for now. Let me know if I should change anything.

**Comment by shivammathur** [comment]
@AegirLeet Thanks for the contribution 🚀

**Pull request merged**
